### ISSUE TITLE
现在的X网指定profile只能看一定的tweet，这个能突破限制？？？

### ISSUE THREAD

**Issue by zzz6519003** [ayanamists/oh-my-old-tweet#1]

**Comment by ayanamists** [comment]
看起来你说的限制只是在前端生效，而且 media 页面似乎是不受影响的。一些下载器（比如 [gallery-dl](https://github.com/mikf/gallery-dl)）仍然可以下载某个用户的全部推文。

这个项目的主要目的是查看被删除的推文，主动从 twitter.com 爬取推文的功能（计划是提供一个后端）仍然在开发中。由于作者最近学业繁忙，这个功能可能得明年才能提供，如果你有相关需要，可以使用 gallery-dl.

-----------

It seems that the restrictions you mentioned only apply to the front-end, and the media page seems to be unaffected. Some downloaders (such as [gallery-dl](https://github.com/mikf/gallery-dl)) can still download all tweets from a user.

The main purpose of this project is to view deleted tweets. The function of actively crawling tweets from twitter.com (planned to provide a backend) is still under development. Due to the author's recent busy schedule, this function may not be available until next year. If you have relevant needs, you can use gallery-dl.

(Translation by ChatGPT)

**Comment by zzz6519003** [comment]
awesome, i'm by Nanjing btw XD
